### ISSUE TITLE
workspace icons not showing up

### ISSUE THREAD

**Issue by zen299** [arashsm79/polybar-themes#1]
all the workspaces in polybar show same character set in "icon-default". i use xfce too
since u set icon-default = " " all workspaces show empty spaces
please help

**Comment by arashsm79** [comment]
> all the workspaces in polybar show same character set in "icon-default". i use xfce too
> since u set icon-default = " " all workspaces show empty spaces
> please help

It's probably because you haven't set the name of your workspaces correctly.
In xfce, open up Setting Manager then head to Workspaces, in the General tab you should see the list of your workspaces. Here you can change the name of your workspaces. they should match the name of workspaces in your workspace module in the polybar config file.
for example I the name of my workspaces were w1, w2, w3, w4, ...
in the workspace module I would type:
```
icon-0 = w1;1
icon-1 = w2;2
icon-2 = w3;3
icon-3 = w4;4
icon-4 = w5;5
icon-5 = w6;6
icon-6 = w7;7
icon-7 = w8;8

```
the word before ';' is the name of your workspace and the word after it is the icon of the workspace
you could also simply name your workspaces 1, 2, 3, 4, ...
and go like:
```
icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
```
